name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    # Do not download and install TLAPS over and over again.
    - uses: actions/cache@v1
      id: cache
      with:
        path: tlaps/
        key: tlaps1.4.5
    - name: Extract CommunityModules for TLAPS
      run: unzip CommunityModules.jar -d CommunityModules/
    - name: Get TLAPS
      if: steps.cache.outputs.cache-hit != 'true' # see actions/cache above
      run: wget https://tla.msr-inria.inria.fr/tlaps/dist/current/tlaps-1.4.5-x86_64-linux-gnu-inst.bin
    - name: Install TLAPS
      if: steps.cache.outputs.cache-hit != 'true' # see actions/cache above
      run: |
        chmod +x tlaps-1.4.5-x86_64-linux-gnu-inst.bin
        ./tlaps-1.4.5-x86_64-linux-gnu-inst.bin -d tlaps
    - name: Run TLAPS
      run: tlaps/bin/tlapm --cleanfp -I tlaps/ -I CommunityModules/ BlockingQueue.tla BlockingQueueSplit.tla BlockingQueueFair.tla
    - name: Get (nightly) TLC
      run: wget https://nightly.tlapl.us/dist/tla2tools.jar
    - name: Run TLC
      run: java -Dtlc2.TLC.stopAfter=1800 -Dtlc2.TLC.ide=Github -Dutil.ExecutionStatisticsCollector.id=1efd5c60f238424fa70d124d0c77bbf1 -cp tla2tools.jar tlc2.TLC -workers auto -lncheck final -checkpoint 60 -coverage 60 -tool -deadlock BlockingQueueFair

